version: 2

project_name: cloudflare-ddns

builds:
  - main: ./
    id: cloudflare-ddns
    binary: cloudflare-ddns
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

homebrew_casks:
  - name: cloudflare-ddns
    repository:
      owner: jon-frankel
      name: homebrew-cloudflare-ddns
      token: "{{ .Env.HOMEBREW_PAT_TOKEN }}"
    directory: Casks
    homepage: https://github.com/jon-frankel/cloudflare-ddns
    description: "Dynamic DNS client that keeps a Cloudflare record in sync with your public IP"
    binaries:
      - cloudflare-ddns
    caveats: |
      Run `cloudflare-ddns` once to complete first-time setup, then:
        brew services start cloudflare-ddns

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
