# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareDdns < Formula
  desc "Dynamic DNS client that keeps a Cloudflare record in sync with your public IP"
  homepage "https://github.com/jon-frankel/cloudflare-ddns"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jon-frankel/cloudflare-ddns/releases/download/v0.1.0/cloudflare-ddns_0.1.0_darwin_amd64.tar.gz"
      sha256 "12bb5861d3fe0b31fa7bc93ded1db3bedc1509f41c350edd497161ce1df9c10c"

      define_method(:install) do
        bin.install "cloudflare-ddns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jon-frankel/cloudflare-ddns/releases/download/v0.1.0/cloudflare-ddns_0.1.0_darwin_arm64.tar.gz"
      sha256 "89a3b47726095c15f1d9a56ebdd9a1db4621a5c46c4b13a176e104f6646aa7fa"

      define_method(:install) do
        bin.install "cloudflare-ddns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jon-frankel/cloudflare-ddns/releases/download/v0.1.0/cloudflare-ddns_0.1.0_linux_amd64.tar.gz"
      sha256 "8fde73cd0591cd55682cd639a5d24c65e1b8ba628beedac2d1c9c5d5b7196f66"
      define_method(:install) do
        bin.install "cloudflare-ddns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jon-frankel/cloudflare-ddns/releases/download/v0.1.0/cloudflare-ddns_0.1.0_linux_arm64.tar.gz"
      sha256 "ffcec29b3da67b7914a881bd719bfd7e8afd0c1e1598539693b4d95a51d0d027"
      define_method(:install) do
        bin.install "cloudflare-ddns"
      end
    end
  end

  def caveats
    <<~EOS
      Run `cloudflare-ddns` once to complete first-time setup, then:
        brew services start cloudflare-ddns
    EOS
  end

  service do
    run [opt_bin/"cloudflare-ddns", "run"]
    keep_alive true
    log_path var/"log/cloudflare-ddns.log"
    error_log_path var/"log/cloudflare-ddns.log"
  end

  test do
    system "#{bin}/cloudflare-ddns", "--version"
  end
end
